### ISSUE TITLE
OOM error on depth image creation step A5000

### ISSUE THREAD

**Issue by chris-aeviator** [epitaque/dreambooth_depth2img#7]
I'm running into out of memory errors at the depth image creation step when following the code in the example.ipynb

This is on a 24 GB A5000. Any idea what could cause this?

## Update
I'm getting the A5000 to 99% VRAM usage when setting the img resolution to 256x256 - this shouldnt be right?

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A5000    On   | 00000000:00:05.0 Off |                  Off |
| 30%   44C    P2   200W / 230W |  23602MiB / 24564MiB |     98%      Default
```

## Logs

```
``For each image in /opt/training/class/, creating a depth image.
100%|_________________________________________________________________________________________________________________________________________________________| 200/200 [00:00<00:00, 127836.15it/s]
Steps:   0%|_                                                                                                                                  | 1/800 [00:02<34:11,  2.57s/it, loss=0.285, lr=1e-6]
Traceback (most recent call last):
  File "train_dreambooth.py", line 837, in <module>
    main(args)
  File "train_dreambooth.py", line 761, in main
    model_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/opt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/accelerate/utils/operations.py", line 507, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/opt/venv/lib/python3.8/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 424, in forward
    sample, res_samples = downsample_block(
  File "/opt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 777, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "/opt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/diffusers/models/attention.py", line 216, in forward
    hidden_states = block(hidden_states, encoder_hidden_states=encoder_hidden_states, timestep=timestep)
  File "/opt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/diffusers/models/attention.py", line 505, in forward
    hidden_states = self.ff(self.norm3(hidden_states)) + hidden_states
  File "/opt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/diffusers/models/attention.py", line 774, in forward
    hidden_states = module(hidden_states)
  File "/opt/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/diffusers/models/attention.py", line 821, in forward
    return hidden_states * self.gelu(gate)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 23.69 GiB total capacity; 22.30 GiB already allocated; 15.44 MiB free; 22.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   0%|_                                                                                                                                  | 1/800 [00:02<38:06,  2.86s/it, loss=0.285, lr=1e-6]
Traceback (most recent call last):
  File "/opt/venv/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/opt/venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/opt/venv/lib/python3.8/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/venv/bin/python3', 'train_dreambooth.py', '--mixed_precision=fp16', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-2-depth', '--pretrained_txt2img_model_name_or_path=stabilityai/stable-diffusion-2-1-base', '--train_text_encoder', '--instance_data_dir=/opt/training/instance', '--class_data_dir=/opt/training/class/', '--output_dir=/opt/model/output', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=a photo of RfAeq living room', '--class_prompt=a photo of living room', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=1e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--max_train_steps=800']' returned non-zero exit status 1.
root@398ece7c0c5e:/opt/diffusers/examples/dreambooth#
[0] 0:bash*Z                                                                                                                                                        
```

**Comment by epitaque** [comment]
No idea, I am able to run it on my 24gb 3090. Do you have xformers + bitsandbytes installed?

**Comment by chris-aeviator** [comment]
@epitaque thanks that was it - I was missing xformers in the GPU container
